# Generated by Django 3.2.4 on 2021-08-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_hub', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='intro',
            field=models.CharField(max_length=255),
        ),
    ]
