# Generated by Django 3.2.4 on 2021-08-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=60)),
                ('occupation', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('signUpDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
